### ISSUE TITLE
(gl:get-integer :max-varying-floats) fails, but other calls to gl:get-integer succeed.

### ISSUE THREAD

**Issue by MonadMania** [3b/cl-opengl#114]
The error message is:

Unknown query enum: MAX-VARYING-FLOATS
   [Condition of type SIMPLE-ERROR]

Similar calls to gl:get-integer succeed, so this isn't a problem with how or where the function is being called.

When I switch to an earlier context, like 3.3, the problem persists.

**Comment by 3b** [comment]
GL spec renamed it to `MAX_VARYING_COMPONENTS` in 3.0 or so (`:max-varying-components` in cl-opengl), so missed the old name in the wrappers. Will add `:max-varying-floats` though, so that should work as well once i push it in a bit.
