### ISSUE TITLE
Can not work on Windows7,emacs,SBCL.Please Help

### ISSUE THREAD

**Issue by segatecm** [3b/cl-opengl#52]
I use quicklisp install it, but report this message:
Unable to load any of the alternatives:
   ("freeglut.dll" "libglut.dll" "libglut-0.dll")
   [Condition of type CFFI:LOAD-FOREIGN-LIBRARY-ERROR]

And I download freeglut.dll and put it into system/system32, but the same error was report.
i download freeglut from this website
http://files.transmissionzero.co.uk/software/development/GLUT/freeglut-MSVC-2.8.1-1.mp.zip

maybe my work is wrong, please help!

**Comment by luismbo** [comment]
I compiled this DLL a long time ago. Maybe it still works? https://common-lisp.net/~loliveira/tmp/freeglut.dll

**Comment by ezrarush** [comment]
is your os 64 bit?

put the dill in a local folder that is in the searched paths... maybe sbcl folder for sbcl

**Comment by segatecm** [comment]
I put the freeglut.dll into sbcl folder and it works now!
thanks @lusimbo and @ezrarush
