### ISSUE TITLE
Possible enum value issues for :timeout-ignored & :timeout-ignored-apple

### ISSUE THREAD

**Issue by cbaggers** [3b/cl-opengl#80]
`%gl:enum` is defined as an `:unsigned-int` however the values for `:timeout-ignored` and `:timeout-ignored-apple` are

```
  (:timeout-ignored #xFFFFFFFFFFFFFFFF)
  (:timeout-ignored-apple #xFFFFFFFFFFFFFFFF)
```
which is outside the unsigned 32bit int range. Should these be #xFFFFFFFF ?

**Comment by cbaggers** [comment]
hmm actually glClientSync does take an unsigned 64bit int

and the definition of the value in [here](https://www.khronos.org/registry/OpenGL/api/GL/glcorearb.h) is:
```
#define GL_TIMEOUT_IGNORED                0xFFFFFFFFFFFFFFFFull
```
So I guess it's more that this doesnt really belong in enum?

**Comment by 3b** [comment]
added gl:+timeout-ignored+ and a few similar constants for those (leaving it in %gl:enum for now since that is autogenerated though)
