### ISSUE TITLE
Wrap direct-state-access functions and other niceties

### ISSUE THREAD

**Issue by mfiano** [3b/cl-opengl#87]
This issue is to serve as a reminder for some useful things that have yet to be added by the maintainer or myself via a PR. I will continue to update this issue as I find more changes that would be nice to have. Please leave this issue open until all items have been accounted for, unless it is decided that they don't fit the scope of this library.

## Direct State Access function
The bindings package has everything generated for us, but we are missing most of the high-level lispy package wrappers. Currently, the following should be written:

The more useful ones include:

-  `glNamedBufferData`
-  `glBindVertexBuffer`
-  `glVertexArrayVertexBuffer`
- `glNamedFramebufferDrawBuffers`
- `glPushDebugGroup`
- `glPopDebugGroup`
- `glNamedRenderbufferStorage`
- `glNamedFramebufferRenderbuffer`

**Comment by 3b** [comment]
skipping some of these for now, since they might conflict with the `glarray` buffer management stuff in cl-opengl, and that needs more thought:
 `glNamedBufferData`, `glBindVertexBuffer`, `glVertexArrayVertexBuffer` (and plural variants)

filed #90 and #91 for the missing parts

**Comment by mfiano** [comment]
@3b I have tested this branch and all seems to work well. It seems I forgot to include a few functions that need to be wrapped. I removed the completed ones, and added a few more. The new ones are:
- `glNamedFramebufferDrawBuffers`
- `glPushDebugGroup`
- `glPopDebugGroup`
- `glNamedRenderbufferStorage`
- `glNamedFramebufferRenderbuffer`

**Comment by mfiano** [comment]
@3b Sometime like this would be needed for `glPushDebugGroup` and `glPopDebugGroup`. Note that I would change it or document that it probably shouldn't be used outside of the ASCII set:
```lisp
(defmacro with-debug-group (name &body body)
  (a:once-only (name)
    `(progn
       (cffi:with-foreign-string (s ,name)
         (%gl:push-debug-group :debug-source-application 0 (length ,name) s))
       (unwind-protect (progn ,@body)
         (%gl:pop-debug-group)))))
```
