### ISSUE TITLE
glGetShaderiv in cl-opengl

### ISSUE THREAD

**Issue by noloop** [3b/cl-opengl#88]
How to I do this in cl-opengl:

`glGetShaderiv(shader, GL_COMPILE_STATUS, &compiled);
`

I don't found any function called "get-shader-iv", is there one reason for this? Is there other function that do the same that *glGetShaderiv*?

**Comment by 3b** [comment]
```lisp
   (gl:get-shader shader :compile-status) ;; returns generalized boolean where applicable
```

Generally, functions exposed from the `GL:` package drop type suffixes like `iv` when possible. If you use slime, symbol completion can usually be used to figure out the names if it isn't obvious.

You can also call `%gl:get-shader-iv` directly, but then you have to deal with manually allocating foreign memory so you can pass a pointer for `&compiled`.

**Comment by noloop** [comment]
@3b 

Thanks, then I can make `(gl:get-program program :active-uniforms)`, I want say: Is it valid for all parameters of information of the "glGetShaderiv" and "glGetProgramiv"?

**Comment by 3b** [comment]
Right, it should work for any valid arguments. If you find any that don't work, please file an issue so it can be fixed.
